### PR TITLE
User commands and loading config file

### PR DESCRIPTION
**Pull request by bookdude13**
Completes #3. Requires proton_cli commit a87f862d9a9539ac342a918fb79c721ae8d12737 on branch meta_changes (latest commit as of this post). Checkout this commit, then run `cargo install --force` to use it.

### CODE REVIEW

**Comment by kayla-e774** [comment]
Hi Ryan!

I have a few questions on a couple of odd things that seem to be happening as I look at the code:

When I try to compile anything in the project (even the code in the handlers directory), I'm getting an error that looks like this:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

The path in the error message looks pretty odd to me. It might be an issue that's unique to my machine and setup, though.

Also, I was unable to checkout the meta_changes branch even though I'm able to see that it exists by looking at the proton-cli repository on the website. (Any 'git pull' I ran was Already up-to-date, however.)

I'd like to know if you'd have any ideas on what could be causing these things!

Thanks a ton,
Kayla

**Comment by bookdude13** [comment]
The first one might be related to you not checking out the meta_changes branch and running cargo install: rust can't find the proton-cli binary, so you get a No such file or directory error (my best guess). To get the branch you should run `git checkout meta_changes`. If it's not showing up, try running `git fetch --all` and trying again.

Hopefully that fixes it. If not, let me know and I can think of more stuff to try, aka lots of Google searches :)

Sorry for late response - didn't see this right away.

**Comment by kayla-e774** [comment]
Hey! Sorry it's been awhile; things have been so busy lately. I eventually just removed and re-cloned the proton-cli repo, which solved the problem of not being able to checkout the necessary commit, but the same "no such file" error still happens with the same path when I try and run anything in the iss3_users branch. I'll give it another go in the morning and let you know if I get anywhere.

**Comment by bookdude13** [comment]
No problem, I get it :)

Just re-cloned and found potential issues. 

- Make sure you are in the proton folder before running cargo
- Before using the user commands, you'll need to create a proton project:
1. Change proton.cfg's vixen_folder to point to either the light show or great northern "Sequence Data" folder
2. Run the 'vixen import-layout' command with just the name of the .pro file you want (e.g. GreatNorthern.pro)
3. Run the 'project new' command with appropriate arguments

You should also make sure that libssl-dev is installed.

I really need to make a README or wizard or something for this...in the meantime, lmk if this solves the issue.

**Comment by kayla-e774** [comment]
Is there anything I would have to include in the command besides "cargo run main.rs"??

**Comment by kayla-e774** [comment]
Oh awesome! Thanks! Just a couple more questions: Is it okay to provide a Windows-style path in proton.cfg? Also which directory do I need to be in to run the 'vixen import-layout' command?

**Comment by bookdude13** [comment]
You don't have to specify main.rs. 'cargo run' finds the correct file to
run from (in this case main.rs) automatically

**Comment by kayla-e774** [comment]
Sorry, didn't realize I added that discussion label, actually

**Comment by bookdude13** [comment]
proton vixen import-layout should be run from within the proton directory. Windows-style paths should be fine. If it doesn't work, try escaping the backslashes, e.g. C:\\Users\\Someone vs. C:\Users\Someone

**Comment by kayla-e774** [comment]
When you say proton folder, you mean the proton folder within the proton repo which contains the proton.cfg file? I am running the "proton vixen import-layout GreatNorthern.pro" and for some reason i get an error that says "bash: proton: command not found". I'll keep trying some different things, but I was wondering if you have any suggestions or if there's a stupid mistake that I'm not seeing.

**Comment by kayla-e774** [comment]
Also, the checkout of the proton_cli commit and the install --force worked to the best of my knowledge.

**Comment by bookdude13** [comment]
Try running cargo run vixen import-layout instead. Proton isn't installed,
so you need to either do cargo install or replace 'proton' with 'cargo run'
when running it. The latter is faster, and more common for development.

**Comment by kayla-e774** [comment]
Oddly enough, even with that command, I'm still getting a pretty strange error that looks like this:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(SyntaxError("invalid escape", 1, 62))', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837

I feel like this is a "me problem", and your code is probably fine? I didn't see anything in the pull request that needs to be changed (I also have a limited knowledge of Rust and I've been really busy, so it's possible that I could've missed something as I was reading through.). Is this pull request holding back development in any way?

**Comment by bookdude13** [comment]
That's weird. Guessing something's up with the config file. This PR isn't holding back development, but there's another one ready for after this that makes proton more usable. You could either a) trust the code and pull it in (not recommended), b) get it to work, or c) close this pull request, and I can make a new one with this stuff and some more stuff which might be easier to get running. Your call

**Comment by bookdude13** [comment]
Actually, do you want to try installing the latest version of rust? Terminal command should be `rustup update`. That might be causing some of the issues

**Comment by kayla-e774** [comment]
Okay, I think things are working somewhat normally, even though I'm getting the same error message, meaning I'm getting normal debug information. I'm just having trouble tracing the error. I think the update definitely helped though!

**Comment by bookdude13** [comment]
Same error as before, ParseError?

**Pull request merged**
